# В этой тетрадке мы разобъем все три датасета на train и test

In [2]:
import pandas as pd
import numpy as np

230 -- количество сцен в наших данных

In [3]:
scenes = np.linspace(0, 229, num=230).astype(int)
np.random.shuffle(scenes)

In [4]:
scenes

array([167,  92,  57,  15,  62, 185,  32, 195, 222, 173,  83,  65,  36,
       194, 150,  11,  49,  33,  88,  63,  24, 122, 212,  21,  43, 206,
       182,  18, 130, 153, 197, 229,  69,  96, 157,  37, 217, 132, 100,
       117,  10,  71, 175,  45,  85,  51, 221, 228, 124,  31,  30,   1,
        55, 116, 204, 196, 125, 187,  47, 148, 215, 193, 203,   8, 142,
       209,  80,  68, 166, 165,  79,  61, 149,  54,  90, 176,  70, 115,
       208, 163,  46,  78, 107, 213, 138, 216,  66, 168,  75, 155,  53,
       158, 178, 152, 136, 135,  58, 161, 207,  87,  98, 218, 192, 120,
        91, 170, 199, 113,  59, 109, 179,  40, 108,  86, 202,  44,  13,
       118,  94,   0, 139,   6, 226, 225, 159,  27,  48, 174, 191, 143,
       140, 189, 146,  26, 183, 141, 169,  64,  29,   5, 172,  19, 129,
       137, 144, 131, 180, 114, 210,  81, 190, 147,  84,  82, 112, 110,
         3,  17,  39, 181, 126,  35, 111, 223, 201, 121, 123,  60, 133,
        99,   7,  14, 162,  34, 106, 198, 101,   9, 227,   2,  5

возьмем 80% всех сцен в train и 20% в test

In [5]:
train_size = int(0.8 * 230)

In [6]:
train_scene_id = scenes[0 : train_size]
test_scene_id = scenes[train_size : ]

In [7]:
train_scene_id

array([167,  92,  57,  15,  62, 185,  32, 195, 222, 173,  83,  65,  36,
       194, 150,  11,  49,  33,  88,  63,  24, 122, 212,  21,  43, 206,
       182,  18, 130, 153, 197, 229,  69,  96, 157,  37, 217, 132, 100,
       117,  10,  71, 175,  45,  85,  51, 221, 228, 124,  31,  30,   1,
        55, 116, 204, 196, 125, 187,  47, 148, 215, 193, 203,   8, 142,
       209,  80,  68, 166, 165,  79,  61, 149,  54,  90, 176,  70, 115,
       208, 163,  46,  78, 107, 213, 138, 216,  66, 168,  75, 155,  53,
       158, 178, 152, 136, 135,  58, 161, 207,  87,  98, 218, 192, 120,
        91, 170, 199, 113,  59, 109, 179,  40, 108,  86, 202,  44,  13,
       118,  94,   0, 139,   6, 226, 225, 159,  27,  48, 174, 191, 143,
       140, 189, 146,  26, 183, 141, 169,  64,  29,   5, 172,  19, 129,
       137, 144, 131, 180, 114, 210,  81, 190, 147,  84,  82, 112, 110,
         3,  17,  39, 181, 126,  35, 111, 223, 201, 121, 123,  60, 133,
        99,   7,  14, 162,  34, 106, 198, 101,   9, 227,   2,  5

In [8]:
test_scene_id

array([171,  28, 127,  25, 160, 105,  76, 184,  77,  93, 186,  95, 102,
       103,  50, 177,  16,  72,   4, 128, 188, 219,  20, 156,  12, 119,
        22,  89, 164,  73,  74, 154, 151,  38,  42,  67,  23, 104,  41,
       205, 214, 145, 200,  52, 224, 220])

In [30]:
df = pd.read_csv("/Volumes/HP P800/itmo/Lidar data/data.csv")

df_train = df[df['scene_id'].isin(train_scene_id)]
df_test = df[df['scene_id'].isin(test_scene_id)]

df_train.to_csv("/Volumes/HP P800/itmo/Lidar data/data_train.csv")
df_test.to_csv("/Volumes/HP P800/itmo/Lidar data/data_test.csv")

In [24]:
df_1 = pd.read_csv("/Volumes/HP P800/itmo/Lidar data/data_simple_preprocess_normalize_all_columns.csv", index_col=0)

df_1_train = df_1[df_1['scene_id'].isin(train_scene_id)]
df_1_test = df_1[df_1['scene_id'].isin(test_scene_id)]

df_1_train.to_csv("/Volumes/HP P800/itmo/Lidar data/data_simple_preprocess_normalize_all_columns_train.csv")
df_1_test.to_csv("/Volumes/HP P800/itmo/Lidar data/data_simple_preprocess_normalize_all_columns_test.csv")

In [9]:
df_kdtree = pd.read_csv("/Volumes/HP P800/itmo/Lidar data/data_kdtree_preprocess.csv", index_col=0)

df_kdtree_train = df_kdtree[df_kdtree['scene_id'].isin(train_scene_id)]
df_kdtree_test = df_kdtree[df_kdtree['scene_id'].isin(test_scene_id)]

df_kdtree_train.to_csv("/Volumes/HP P800/itmo/Lidar data/df_kdtree_train.csv")
df_kdtree_test.to_csv("/Volumes/HP P800/itmo/Lidar data/df_kdtree_test.csv")